### PR TITLE
[MULTIARCH-4593] use multiarch base image for promtail

### PR DESCRIPTION
**Pull request by jeffdyoung**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] Documentation added
- [ ] Tests updated
- [ ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
  - **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
- [ ] Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- [ ] For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755d213)
- [ ] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and `deleted-config.yaml` files respectively in the `tools/deprecated-config-checker` directory. [Example PR](https://github.com/grafana/loki/pull/10840/commits/0d4416a4b03739583349934b96f272fb4f685d15)

### CODE REVIEW

**Review by periklis — CHANGES_REQUESTED** [review]
FYI I don't think the `ci/prow`images` is building here the correct image because the [openshift/release](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml#L23-L29) config for this image in `upstream-v2.9.8` replaces the last `FROM` directive with `base-rhel9` again no matter what. Can you double check please that the `ci/prow/images` are actually the ones you want to have? If not you need to patch [openshift/release](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml#L23-L29) first to use multi-arch base image.

**Comment by droslean** [comment]
> > FYI I don't think the `ci/prow`images`is building here the correct image because the [openshift/release](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml#L23-L29) config for this image in`upstream-v2.9.8`replaces the last`FROM`directive with`base-rhel9`again no matter what. Can you double check please that the`ci/prow/images` are actually the ones you want to have? If not you need to patch [openshift/release](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml#L23-L29) first to use multi-arch base image.
> 
> ci-operator can only replace 1 image from a dockerfile, and in this case
> 
> https://github.com/openshift/release/blob/master/ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml#L23-L29 is replacing: https://github.com/openshift/loki/blob/upstream-v2.9.8/Dockerfile.promtail.ocp#L1
> 
> but this image remains https://github.com/openshift/loki/blob/upstream-v2.9.8/Dockerfile.promtail.ocp#L7
> 
> @droslean Can you confirm? If true, is there a better way to handle replacing all of the FROM containers in a multi stage build?

ci-operator should replace both FROM images if the `inputs` configuration is done accordingly.

**Comment by jeffdyoung** [comment]
> images

@droslean what is the next step here?
Should I replace registry.ci.openshift.org/ocp/4.14:base-rhel9 with registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16 [here](https://github.com/openshift/loki/blob/upstream-v2.9.8/Dockerfile.promtail.ocp#L7)

or

close this and try and configure ci-operator override registry.ci.openshift.org/ocp/4.14:base-rhel9

**Comment by droslean** [comment]
> > images
> 
> @droslean what is the next step here? Should I replace registry.ci.openshift.org/ocp/4.14:base-rhel9 with registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16 [here](https://github.com/openshift/loki/blob/upstream-v2.9.8/Dockerfile.promtail.ocp#L7)
> 
> or
> 
> close this and try and configure ci-operator override registry.ci.openshift.org/ocp/4.14:base-rhel9

The images in the Dockerfile should change too. Then in the ci-operator config you can adjust the image inputs to be replaced by the base images.

**Pull request closed without merging**
