### PR TITLE
Update from upstream repository removing go1.20 compatibily patches 

### PR DESCRIPTION
**Pull request by periklis**
The following up syncs up `grafana/main` into `openshift/main` and additionally removes previous go1.20 compatibility patches, i.e.:
```
96e3ca21e fix[compat-1.20]: Remove unused generic code
4e625b0f4 fix[compat-1.20]: Remove min/max generic usage in bloom pkgs
9df89a5a0 fix[compat-1.20]: Remove clear usage in bloom-tester pkg
567007dba fix[compat-1.20]: Remove clear usage in logql pkg
25f030156 fix[compat-1.20]: Remove clear usage in logql pkg
06e39d30d fix[compat-1.20]: Fix mod file and remove stdlib clear usage
60cdd365b fix[compat-1.20]: Remove context.WitTimeoutCause occurences
9f5f65ba7 fix[compat-1.20]: Remove stdlib pkg cmp occurences
```

Depends on:
- openshift/release/pull/48731

Refs:
- [LOG-5061](https://issues.redhat.com//browse/LOG-5061)

### CODE REVIEW

**Comment by periklis** [comment]
Holding for a moment to investigate why on earth image building and tests pass with a go1.20 binary :thinking:

**Comment by periklis** [comment]
Came to the conclusion that the above tests and image building works because:
1. `ci/prow/test` succeeds only the Loki Operator test and this one is still 1.20 based so :heavy_check_mark: 
2. `ci/prow/images` succeeds because this PR bumps the `FROM` directives in `Dockerfile.ocp` and `Dockerfile.promtail.ocp` already to `rhel-9-golang-1.21-openshift-4.16` and thus we do not immediately require the openshift/release PR.

**Comment by xperimental** [comment]
/retitle Update from upstream repository removing go1.20 compatibility patches

**Pull request merged**
